title: Omar Garib
description: Multimodal intelligent systems · human-in-the-loop autonomy · speech/vision/3D reasoning · social & assistive robotics
url: https://omargarib02.github.io
lang: en
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "contrast"
plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
author:
  name: Omar Garib
  avatar: /assets/img/headshot.jpg
  email: ogarib@gatech.edu
  bio: false  # Hide bio in sidebar since it's in main content
  links:
    - label: CV
      icon: far fa-file-alt
      url: /assets/cv/Omar_Garib_CV.pdf
    - label: GitHub
      icon: fab fa-github
      url: https://github.com/omargarib02
    - label: LinkedIn
      icon: fab fa-linkedin
      url: https://www.linkedin.com/in/omargarib/
    - label: Email
      icon: fas fa-envelope
      url: mailto:ogarib@gatech.edu
defaults:
  - scope:
      path: ""
    values:
      layout: single
      toc: false
      author_profile: true  # Ensure this is true for all pages
      comments: false
  - scope:
      path: ""
      type: pages
    values:
      author_profile: true
      sidebar:
        - title: "News"
          text: |
            <ul style="list-style: none; padding: 0; margin: 0; font-size: 0.9rem;">
              <li style="margin: 0.8rem 0; line-height: 1.4;"><strong style="display: block; margin-bottom: 0.2rem;">September 2025</strong>Began research effort on designing an effective, personalized AI companion for the elderly.</li>
              <li style="margin: 0.8rem 0; line-height: 1.4;"><strong style="display: block; margin-bottom: 0.2rem;">September 2025</strong>Submitted <strong>AIRHILT</strong> to ICRA.</li>
              <li style="margin: 0.8rem 0; line-height: 1.4;"><strong style="display: block; margin-bottom: 0.2rem;">August 2025</strong>Two <strong>AIAA SciTech</strong> abstracts accepted.</li>
              <li style="margin: 0.8rem 0; line-height: 1.4;"><strong style="display: block; margin-bottom: 0.2rem;">May 2025</strong>Began research collaboration with <strong>NASA Langley</strong> (Digital Transformation).</li>
            </ul>
timezone: America/New_York
