title: Omar Garib
description: Multimodal intelligent systems · human-in-the-loop autonomy · speech/vision/3D reasoning · social & assistive robotics
url: https://omargarib02.github.io
lang: en

remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "contrast"

plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false

author:
  name: Omar Garib
  avatar: /assets/img/headshot.jpg          # keep this; CSS makes it rectangular & larger
  email: ogarib@gatech.edu
  links:
    - label: CV
      icon: far fa-file-alt
      url: /assets/cv/Omar_Garib_CV.pdf
    - label: GitHub
      icon: fab fa-github
      url: https://github.com/omargarib02
    - label: LinkedIn
      icon: fab fa-linkedin
      url: https://www.linkedin.com/in/omargarib/

defaults:
  - scope:
      path: ""
    values:
      layout: single
      toc: false
      author_profile: false
      comments: false

timezone: America/New_York
